"""add initial db tables

Revision ID: 867acd82e159
Revises: 
Create Date: 2026-01-17 15:29:20.733603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '867acd82e159'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('base_priority', sa.Integer(), nullable=True),
    sa.Column('default_sla_hours', sa.Integer(), nullable=True),
    sa.Column('workflow_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('workflow_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('task_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_active', 'workflow_instances', ['current_state', 'expires_at'], unique=False)
    op.create_index('idx_workflow_user', 'workflow_instances', ['user_id', 'workflow_type', 'current_state'], unique=False)
    op.create_index(op.f('ix_workflow_instances_session_id'), 'workflow_instances', ['session_id'], unique=False)
    op.create_table('priority_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type_id', sa.Integer(), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('condition_field', sa.String(length=100), nullable=True),
    sa.Column('condition_operator', sa.String(length=20), nullable=True),
    sa.Column('condition_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('priority_level', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('evaluation_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_task_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('task_type_id', sa.Integer(), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_action', sa.Boolean(), nullable=True),
    sa.Column('priority_boost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'task_type_id', name='uq_role_task')
    )
    op.create_table('saga_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_instance_id', sa.UUID(), nullable=True),
    sa.Column('saga_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('completed_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type_id', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('reference_table', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('calculated_priority', sa.Integer(), nullable=True),
    sa.Column('priority_level', sa.String(length=20), nullable=True),
    sa.Column('assigned_role_id', sa.Integer(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_priority_calc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_pending', 'work_items', ['assigned_role_id', 'status', 'calculated_priority'], unique=False)
    op.create_index('idx_status_priority', 'work_items', ['status', 'calculated_priority'], unique=False)
    op.create_table('workflow_state_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_instance_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=False),
    sa.Column('trigger_event', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saga_step_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('saga_instance_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compensation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('compensated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['saga_instance_id'], ['saga_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saga_step_results')
    op.drop_table('workflow_state_history')
    op.drop_index('idx_status_priority', table_name='work_items')
    op.drop_index('idx_role_pending', table_name='work_items')
    op.drop_table('work_items')
    op.drop_table('saga_instances')
    op.drop_table('role_task_assignments')
    op.drop_table('priority_rules')
    op.drop_index(op.f('ix_workflow_instances_session_id'), table_name='workflow_instances')
    op.drop_index('idx_workflow_user', table_name='workflow_instances')
    op.drop_index('idx_workflow_active', table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_table('task_types')
    # ### end Alembic commands ###